### PR TITLE
Added instructions to install on MySQL Server

### PR DESCRIPTION
**Pull request by philip**
Not sure if this is the best solution or way you want it written, but, I believe this to be true. At least, it worked for me :)

### CODE REVIEW

**Comment by federico-razzoli** [comment]
Bulls & Cows uses SEQUENCE storage engine, which doesn't compile on MySQL.

But if other games work as they are or with small changes (like this one), it's worth writing it in the README. Just specify which game you made work and which MySQL version(s).

**Comment by philip** [comment]
Well that's embarrassing, I assume I'd have edited anagram's README but clearly did not... hopefully the second time around will be more successful :)

**Comment by federico-razzoli** [comment]
Actually you edited the global README. This could mean that the current readme structure is confusing, so feel free to reorganise it in a cleared way, if you like. In a separate PR.

**Comment by philip** [comment]
Yep, that was the embarrassing part ;)

**Comment by federico-razzoli** [comment]
Hey @philip , some time passed. I am closing this PR. Feel free to file another, editing the correct file.

**Pull request closed without merging**
